# This file was generated by GoReleaser. DO NOT EDIT.
class Gotk < Formula
  desc "GitOps Toolkit CLI"
  homepage "https://toolkit.fluxcd.io/"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fluxcd/toolkit/releases/download/v0.1.0/gotk_0.1.0_darwin_amd64.tar.gz"
    sha256 "db238ac5e74c38bbf080227978b3b313c4fe28a741d5cb42eddf84c6599d95e2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fluxcd/toolkit/releases/download/v0.1.0/gotk_0.1.0_linux_amd64.tar.gz"
      sha256 "17f28d0112d59019bf09f821b19a9e72f8351e5d80eadab6636120199e7df8cb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fluxcd/toolkit/releases/download/v0.1.0/gotk_0.1.0_linux_arm64.tar.gz"
        sha256 "6d953175cc074858cbe58e765866e3f07dae493d3a0f6719b6d51b62c86b3102"
      else
      end
    end
  end
  
  depends_on "kubectl" => :optional

  def install
    bin.install "gotk"
  end

  test do
    system "#{bin}/gotk --version"
  end
end
