# This file was generated by GoReleaser. DO NOT EDIT.
class Gotk < Formula
  desc "GitOps Toolkit CLI"
  homepage "https://toolkit.fluxcd.io/"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fluxcd/toolkit/releases/download/v0.1.5/gotk_0.1.5_darwin_amd64.tar.gz"
    sha256 "7a7a5e5d97c51ae9e5cfec589e51e12b3fe333fd27d655ff657b5d3b27de7db5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fluxcd/toolkit/releases/download/v0.1.5/gotk_0.1.5_linux_amd64.tar.gz"
      sha256 "b23fb794b30a0758307858eb3f8f1e336a45b4a08d912b075261c36c17ab0546"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fluxcd/toolkit/releases/download/v0.1.5/gotk_0.1.5_linux_arm64.tar.gz"
        sha256 "51448fe3f220ca32088d60afb372aa79461f01b29c487d0386787d3822d91913"
      else
      end
    end
  end
  
  depends_on "kubectl" => :optional

  def install
    bin.install "gotk"
  end

  test do
    system "#{bin}/gotk --version"
  end
end
