# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "GitOps Toolkit CLI"
  homepage "https://toolkit.fluxcd.io/"
  version "0.0.25"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fluxcd/toolkit/releases/download/v0.0.25/gotk_0.0.25_darwin_amd64.tar.gz"
    sha256 "87003b511df4b8b54550759ed3dd1ed6087c952653161e7e97f982ff38cc6b80"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fluxcd/toolkit/releases/download/v0.0.25/gotk_0.0.25_linux_amd64.tar.gz"
      sha256 "e513ad5f29f30126d746010dd3cbc245bd7be9b61480269867d9de987f648c70"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fluxcd/toolkit/releases/download/v0.0.25/gotk_0.0.25_linux_arm64.tar.gz"
        sha256 "e75c5f7ac11903ced6da3312c0e55bab15f39f8be2a0106c926ac795db9c4bde"
      else
      end
    end
  end
  
  depends_on "kubectl" => :optional

  def install
    bin.install "gotk"
  end

  test do
    system "#{bin}/gotk --version"
  end
end
